<?xml version="1.0"?>
<package format="3">
  <name>listener</name>
  <version>0.0.1</version>
  <description>ROS2 C++ listener example</description>

  <maintainer email="jorgen.fjermedal@hotmail.com">jorgen fjermedal</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
