<?xml version="1.0"?>
<robot name="simple_person" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--
    This URDF defines a simple person model.
    It is designed in a standard "Z-up" (ENU) reference frame.
    The root link has been renamed to 'person_enu_link' to avoid conflicts
    and make its coordinate system convention explicit.
  -->

  <!-- Constants for the model -->
  <xacro:property name="torso_height" value="0.7" />
  <xacro:property name="torso_radius" value="0.15" />
  <xacro:property name="head_radius" value="0.12" />
  <xacro:property name="arm_length" value="0.6" />
  <xacro:property name="arm_radius" value="0.05" />
  <xacro:property name="leg_length" value="0.8" />
  <xacro:property name="leg_radius" value="0.06" />

  <!-- Base Link (at the feet, defined in an ENU frame) -->
  <link name="person_enu_link" />

  <!-- Torso Link -->
  <joint name="torso_joint" type="fixed">
    <parent link="person_enu_link"/>
    <child link="torso_link"/>
    <origin xyz="0 0 ${leg_length + torso_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="torso_link">
    <visual>
      <geometry>
        <cylinder length="${torso_height}" radius="${torso_radius}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <!-- Head Link -->
  <joint name="head_joint" type="fixed">
    <parent link="torso_link"/>
    <child link="head_link"/>
    <origin xyz="0 0 ${torso_height/2 + head_radius}" rpy="0 0 0"/>
  </joint>

  <link name="head_link">
    <visual>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <!-- Right Arm Link -->
  <joint name="right_arm_joint" type="fixed">
    <parent link="torso_link"/>
    <child link="right_arm_link"/>
    <origin xyz="0 ${-torso_radius - arm_radius} ${torso_height/2 - arm_radius}" rpy="${-pi/2} 0 0"/>
  </joint>

  <link name="right_arm_link">
    <visual>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- Left Arm Link -->
  <joint name="left_arm_joint" type="fixed">
    <parent link="torso_link"/>
    <child link="left_arm_link"/>
    <origin xyz="0 ${torso_radius + arm_radius} ${torso_height/2 - arm_radius}" rpy="${pi/2} 0 0"/>
  </joint>

  <link name="left_arm_link">
    <visual>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- Right Leg Link -->
  <joint name="right_leg_joint" type="fixed">
    <parent link="person_enu_link"/>
    <child link="right_leg_link"/>
    <origin xyz="0 ${-torso_radius/2} ${leg_length/2}" rpy="0 0 0"/>
  </joint>

  <link name="right_leg_link">
    <visual>
      <geometry>
        <cylinder length="${leg_length}" radius="${leg_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Left Leg Link -->
  <joint name="left_leg_joint" type="fixed">
    <parent link="person_enu_link"/>
    <child link="left_leg_link"/>
    <origin xyz="0 ${torso_radius/2} ${leg_length/2}" rpy="0 0 0"/>
  </joint>

  <link name="left_leg_link">
    <visual>
      <geometry>
        <cylinder length="${leg_length}" radius="${leg_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

</robot>
